### ISSUE TITLE
Upstreaming footprints

### ISSUE THREAD

**Issue by Duckle29** [ai03-2725/MX_Alps_Hybrid#11]
Hey there. I was wondering if you'd be interested in upstreaming these footprints to KiCAD. I try my hardest to only use KiCAD parts, as it makes it easier to share my projects, and as such would love for these to be upstreamed.

If you need someone to deal with the PR to kicad I can happily help out with that, though I don't really know how I'd go about that.

I think as a first step I'd try and fork your repo and see what work would be needed for it to mostly conform with the [KLC](http://kicad-pcb.org/libraries/klc/), but before I put too much work into it, I'd want to know if you'd be interested in attempting to upstream the footprints? :)

**Comment by perigoso** [comment]
Working on merging them to the official libraries.

This work is being done in a seperate repo at [perigoso/MX_Alps_Hybrid](https://github.com/perigoso/MX_Alps_Hybrid)

TODO:
- [x] Merge #15 (as well as @WardBenjamin changes)
- [ ] Rename footprints to comply with KiCad standard
- [ ] Verify footprints compliance with [KLC](https://kicad-pcb.org/libraries/klc/)
- [ ] Move footprints to fork of [KiCad/kicad-footprints](https://github.com/KiCad/kicad-footprints)
- [ ] Submit a PR

I'm open to suggestions / help.

**Comment by ai03-2725** [comment]
Apologize for the ridiculous delay; finally got around to checking pending issues and PRs after too long.  
I'm not sure if it's best to make these official, since quite a few redundant footprints exist (i.e. entire duplicate collections with and without LEDs) solely for the purpose of speeding up PCB development for my own specific workflow and maintaining compatibility with old projects when updating this repository's components.  
In the future as switch types and footprint variants grow to meet various designer requirements, the library will most definitely fail to meet the requirements of the official footprint guidelines.

**Comment by perigoso** [comment]
part of the process of upstreaming was to make the footprints consistent and compliant with standar, as well as remove things like the led/no led, in the end i forked the library and make everything from scratch and implemented scripts for the generation, making it easy to modify them and add new ones in the future, could do with some work but its pretty good right now.

https://github.com/perigoso/keyswitch-kicad-library

the process of upstreaming was going well, but the lack of time from the time from the maintainers stalled and its pending to this day
