### ISSUE TITLE
Use oval holes in the hybrid MX-Alps footprints

### ISSUE THREAD

**Issue by dsanchezseco** [ai03-2725/MX_Alps_Hybrid#14]
Why not use one oval hole for the hybrids instead of two overlaping pads/holes??
With the oval ones you can also get rid of the kicad drc errors about the drilled holes being to close.

I can PR if you will.

It would be something like this 
![image](https://user-images.githubusercontent.com/20790609/82117166-d2f9bb80-976e-11ea-93a2-395198dbf31d.png)

**Comment by ai03-2725** [comment]
Apologize for the ridiculous delay; finally got around to checking pending PRs after too long.  
Oval holes were purposely avoided due to past experiences with end users struggling to solder switches in large open pads.
Since the double-hole configuration has had positive real-world feedback from users and many existing PCB projects depend on the current style., I will keep them as double-hole unless the PR is to add a separate module (i.e. MX_Alps_Hybrid_Oval.pretty) to offer it as an option.
